#!/sbin/busybox sh

export BOOTREC_EVENT_NODE="/dev/input/event2 c 13 66"
export BOOTREC_EVENT="/dev/input/event2"
export BOOTREC_FOTA_NODE="/dev/block/mmcblk0p13 b 179 13"
export BOOTREC_FOTA="/dev/block/mmcblk0p13"
