#!/sbin/busybox sh

g=green
trig(){
for i in $3 $4 $5 $6
do
	echo $i > /sys/class/leds/$1-key-$2/brightness
	busybox sleep $t
done
}

# trigger LED bar
t=0.2
trig l red 10 80 160 255
trig m red 20 60 120 200 & trig m $g 10 30 60 100
trig r $g 10 80 160 255
busybox sleep 0.8

# trigger vibration
echo 50 > /sys/class/timed_output/vibrator/enable

# turn off LED bar
t=0
trig l red 0
trig m red 0
trig m $g 0
trig r $g 0
