#!/sbin/sh


# Trigger button-backlight
echo '255' > /sys/class/leds/l-key-blue/brightness
echo '255' > /sys/class/leds/m-key-blue/brightness
echo '255' > /sys/class/leds/r-key-blue/brightness
echo '255' > /sys/class/leds/l-key-green/brightness
echo '255' > /sys/class/leds/m-key-green/brightness
echo '255' > /sys/class/leds/r-key-green/brightness
echo '255' > /sys/class/leds/l-key-red/brightness
echo '255' > /sys/class/leds/m-key-red/brightness
echo '255' > /sys/class/leds/r-key-red/brightness


# Trigger white, red, orange, yellow, green, blue, purple LEDs
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-red/brightness
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-green/brightness
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-blue/brightness
usleep 300000
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-blue/brightness
usleep 300000
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-red/brightness
echo '50' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-blue/brightness
usleep 300000
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-red/brightness
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-blue/brightness
usleep 300000
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-red/brightness
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-blue/brightness
usleep 300000
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-green/brightness
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-blue/brightness
usleep 300000
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-green/brightness
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-blue/brightness
usleep 300000


# Trigger vibration
echo '200' > /sys/class/timed_output/vibrator/enable


# Disable button-backlight
echo '0' > /sys/class/leds/l-key-blue/brightness
echo '0' > /sys/class/leds/m-key-blue/brightness
echo '0' > /sys/class/leds/r-key-blue/brightness
echo '0' > /sys/class/leds/l-key-green/brightness
echo '0' > /sys/class/leds/m-key-green/brightness
echo '0' > /sys/class/leds/r-key-green/brightness
echo '0' > /sys/class/leds/l-key-red/brightness
echo '0' > /sys/class/leds/m-key-red/brightness
echo '0' > /sys/class/leds/r-key-red/brightness


# Disable LEDs
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/pwr-blue/brightness


cat /dev/input/event2 > /dev/keycheck &
sleep 3
kill -9 $!
